site_name: "Netzwerktechnik"
site_url: https://netzwerktechnik.pages.dev/
repo_name: felbinger/netzwerktechnik
repo_url: https://github.com/felbinger/netzwerktechnik/
site_description: "Netzwerktechnik"
site_author: https://github.com/felbinger
edit_uri: https://github.dev/felbinger/netzwerktechnik/blob/main/docs

theme:
  name: 'material'
  palette:
    - scheme: slate
      primary: 'blue'

  font:
    text: Roboto
    code: Roboto Mono

  language: de
  direction: ltr
  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.expand
    - navigation.instant
    - navigation.sections

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list   # image resize and lazy loading
  - md_in_html  # center images, add caption

plugins:
  - git-revision-date
  - git-revision-date-localized
